version: '3.3'

services:
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/config/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        depends_on:
            - php
        networks:
            ipvxinterfacenet:
                ipv4_address: 10.10.10.11

    php:
        build: ./docker/php
        restart: always
        volumes:
            - .:/var/www/html
        links:
            - mysql:mysql
        depends_on:
            - mysql
            - redis
        networks:
            ipvxinterfacenet:
                ipv4_address: 10.10.10.12

    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        command: --init-file /data/application/init.sql
        volumes:
            - ./docker/mysql_init.sql:/data/application/init.sql
            - ./docker/data/mysql:/var/lib/mysql
            - .:/var/www/html
        environment:
            MYSQL_ROOT_PASSWORD: ipvxinterface
            MYSQL_DATABASE: ipvxinterface
            MYSQL_USER: ipvxinterface
            MYSQL_PASSWORD: ipvxinterface
            MYSQL_ROOT_HOST: '%'
        networks:
            ipvxinterfacenet:
                ipv4_address: 10.10.10.13

    redis:
        image: 'redis:4-alpine'
        restart: always
        command: redis-server --requirepass redis_password
        ports:
            - "6379:6379"
        expose:
            - 6379
        networks:
            ipvxinterfacenet:
                ipv4_address: 10.10.10.14

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8000:80"
        expose:
            - "8000"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        networks:
            ipvxinterfacenet:
                ipv4_address: 10.10.10.15

    worker:
        build: ./docker/worker
        restart: always
        volumes:
            - .:/var/www/html
            - ./docker/worker/config:/etc/supervisor/conf.d
        links:
            - mysql:mysql
        depends_on:
            - mysql
            - redis
        networks:
            ipvxinterfacenet:

networks:
    ipvxinterfacenet:
        driver: bridge
        ipam:
            config:
                -   subnet: 10.10.10.0/24
                    gateway: 10.10.10.1
