name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          extensions: curl, fileinfo, imagick, imap, json, pdo
      - name: Install Node.js dependencies
        run: npm ci
      - name: Publish Aurora theme assets
        run: npm run production
      - name: Install PHP dependencies
        run: composer install
      - name: Generate API documentation
        run: php artisan l5-swagger:generate
      - name: Set API documentation version
        run: sed -i "s/0.0.0/$TAG/g" storage/api-docs/api-docs.json
        env:
          TAG: ${{ github.ref_name }}
      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Generate ERD
        run: php artisan generate:erd storage/api-docs/erd.svg --format=svg
      - name: Copy API documentation
        run: |
          mkdir -p docs
          cp storage/api-docs/api-docs.json docs/api-docs-${{ github.ref_name }}.json
          cp storage/api-docs/api-docs.json docs/api-docs-latest.json
          cp storage/api-docs/erd.svg docs/erd-${{ github.ref_name }}.svg
          cp storage/api-docs/erd.svg docs/erd-latest.svg
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: api.getobms.com
          keep_files: true
          publish_branch: gh-pages
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build and push app image
        run: |
          docker build -t ghcr.io/obms-open-business-management-software/core-app:${{ github.ref_name }} -f docker/production/Dockerfile.fpm .
          docker push ghcr.io/obms-open-business-management-software/core-app:${{ github.ref_name }}
          docker tag ghcr.io/obms-open-business-management-software/core-app:${{ github.ref_name }} ghcr.io/obms-open-business-management-software/core-app:latest
          docker push ghcr.io/obms-open-business-management-software/core-app:latest
      - name: Build and push worker image
        run: |
          docker build -t ghcr.io/obms-open-business-management-software/core-worker:${{ github.ref_name }} -f docker/production/Dockerfile.worker .
          docker push ghcr.io/obms-open-business-management-software/core-worker:${{ github.ref_name }}
          docker tag ghcr.io/obms-open-business-management-software/core-worker:${{ github.ref_name }} ghcr.io/obms-open-business-management-software/core-worker:latest
          docker push ghcr.io/obms-open-business-management-software/core-worker:latest
